#!/usr/bin/env php
<?php
	define('VERSION', '0.1a');
	define('BASEDIR', dirname(__FILE__));
	mb_internal_encoding('UTF-8');
    mb_regex_encoding('UTF-8');
    umask(0);

    require_once BASEDIR.'/lib/util/runner.php';
