#!/bin/bash

set -e
set -u

LOG=/tmp/roboticks-tests-log
echo "Launching tests..."
echo "Logging to $LOG"
if [[ -f "$LOG" ]];
then
	mv $LOG $LOG.old
fi;

DIR="$( cd "$( dirname "${BASH_SOURCE[0]:-""}" )" && pwd )"

set +e
for i in $(find $DIR/phpunit -type f -name "*.php");
do
	echo $i;
	phpunit $@ -c $DIR/phpunit.xml $i >> $LOG;
done;
set -e

grep -Po 'FAILURES|incomplete' $LOG
