<?php

/**
 * Bot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robotics
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bot extends BaseBot
{
    public function __toString() {
        return '#'.$this->getId();
    }
}
