<?php

/**
 * Bot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robotics
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bot extends BaseBot
{
    public $controller;

    public function __toString() {
        return '#'.$this->getId();
    }

    public function getController() {
        if (empty($this->controller)) {
            $controllerClass = $this->getControllerClass();
            $clientFilename = sfConfig::get('sf_root_dir').'/client/roboticks';
            $homeDirname = sfConfig::get('sf_cache_dir').'/bots/'.$this->getId();
            $this->controller = new $controllerClass($this, $clientFilename, $homeDirname);
        }
        return $this->controller;
    }
}
