<?php

/**
 * BotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bot');
    }

    public function getActiveBotsQuery() {
        return $this->createQuery('b')
            ->andWhere('b.active_at <= ?', time())
    ;}

    public function getActiveBotsOnDemand() {
        return $this->getActiveBotsQuery()->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }
}
