<?php

/**
 * BotUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BotUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BotUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BotUser');
    }
}