<?php

/**
 * RealmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RealmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RealmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Realm');
    }
}