<?php

/**
 * RealmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RealmTable extends Doctrine_Table
{
    public function getUninitializedRealmsQuery() {
        return $this->createQuery('r')
            ->where('r.initialized = ?', false)
    ;}

    public function getUninitializedRealms() {
        return $this->getUninitializedRealmsQuery()->execute();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object RealmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Realm');
    }

    public function isTheOnlyActiveUser($userId, $realmId) {
        return RobotTable::getInstance()->getActiveOwnedInRealmQuery($userId, $realmId)->groupBy('r.user_id')->count() === 1;
    }
}
