<?php

/**
 * Realm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robotics
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Realm extends BaseRealm
{
    public $controller;

    public $salt = '301fd763d41594cacdedb18b53e265ee';

    public function __toString() {
        return strtr($this->getToStringFormat(), array(
            '%id%' => $this->getId(),
            '%name%' => $this->getName(),
            '%controller_class%' => $this->getControllerClass(),
        ));
    }

    public function getToStringFormat() {
        return '#%id% "%name%" [%controller_class%]';
    }

    public function construct()
    {
        parent::construct();
        $this->initController();
    }

    public function initController() {
        if (sfContext::hasInstance() && !$this->isNew()) {
            $controllerClass = $this->getControllerClass();
            $this->controller = new $controllerClass($this, sfContext::getInstance()->getEventDispatcher());
        }
    }

    public function setController($controller) {
        $this->controller = $controller;
    }

    public function getController() {
        return $this->controller;
    }

    public function setPassword($password) {
        $this->_set('password', $this->generatePassword($password));
    }

    public function checkPassword($password) {
        return $this->password == $this->generatePassword($password);
    }

    public function generatePassword($password) {
        return md5($password.$this->salt);
    }

    public function getOptions() {
        $options = $this->_get('options');
        return $options? $options : array(); // Doctrine returns null rather than empty array   
    }

    /**
     * Available options:
     * - letter_probability
     *
     * @param $name
     * @param null $default
     * @return string
     */
    public function getOption($name, $default = null) {
        $options = $this->getOptions();
        return array_key_exists($name, $options)? $options[$name] : $default;
    }

    public function isMember(User $user) {
        return UserRealmTable::getInstance()->countByUserIdAndRealmId($user->getId(), $this->getId());
    }

    public function getSectorsCount() {
        return SectorTable::getInstance()->countByRealmId($this->getId());
    }

    public function getUsersCount() {
        return UserRealmTable::getInstance()->countByRealmId($this->getId());
    }

    public function getRobotsCount() {
        return RobotTable::getInstance()->countByRealmId($this->getId());
    }

    public function getActiveRobotsCount() {
        return RobotTable::getInstance()->countActiveByRealmId($this->getId());
    }

    public function isTheOnlyActiveUser($userId) {
        return $this->getTable()->isTheOnlyActiveUser($userId, $this->getId());
    }

    public function doWin($userId) {
        $link = UserRealmTable::getInstance()->findOneByRealmIdAndUserId($this->getId(), $userId);
        $link->setIsWinner(true);
        $link->save();
        return $link;
    }

    public function postInsert($event) {
        sfConfig::set('app_realm_id', $this->getId());
        if (sfContext::hasInstance()) {
            $this->initController();
            $this->getController()->getBuilder()->build();
            $this->getController()->addUser($this->getOwner());
        }
        parent::postInsert($event);
    }

}
