<?php

/**
 * Robot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robotics
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Robot extends BaseRobot {
	public function __toString() {
		return '#'.$this->id.' "'.$this->getName().'"';
	}

    public function getName() {
        return (string)$this->getWord();
    }

    public function hasDenotative($denotative) {
        return mb_strpos($this->getName(), $denotative);
    }

	public function toListItem() {
		return array(
			'name' => $this->getName(),
			'sector' => $this->Sector->__toString(),
			'functions' => implode($this->getFunctions())
		) + $this->toArray(false);
	}
	
	public function getFunctions() {
		$functions = array();
		foreach ($this->getTable()->getFunctions() as $meaning=>$denotative) {
			if ($this->hasDenotative($denotative)) {
				$functions[$meaning] = $denotative;
			}
		}
		return $functions;
	}

    public function hasFunction($meaning) {
        return $this->hasDenotative($this->getTable()->getFunctionDenotative($meaning));
    }

	public function calculateSpeed() {
		preg_match_all('/'.implode('|', $this->getTable()->getVowels()).'/u', $this->getName(), $matches, PREG_SET_ORDER);
		return max(0, 3*count($matches) - mb_strlen($this->getName()));
	}

	public function getScanBorders() {
		$base = $this->Sector;
		return array(
			'blX' => $base->x - sfConfig::get('app_scan_size'),
			'blY' => $base->y - sfConfig::get('app_scan_size'),
			'trX' => $base->x + sfConfig::get('app_scan_size'),
			'trY' => $base->y + sfConfig::get('app_scan_size'),
		);
	}

    public function doExtract() {
        $sector = $this->getSector();
        $sector->setDrops($sector->getDrops().$sector->getLetter());
    }

	public function preSave($event) {
		$this->speed = $this->calculateSpeed();
	}

}
