<?php

/**
 * Sector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robotics
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Sector extends BaseSector {
	public function __toString() {
		return $this->x.','.$this->y;
	}

    public function setDropsArray(array $drops) {
        $this->setDrops(implode('', $drops));
    }

    public function getDropsArray() {
        return str_split($this->getDrops());
    }

}
