<?php

/**
 * Sector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robotics
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Sector extends BaseSector {
    public function __toString() {
        return $this->x.','.$this->y;
    }

    public function setDropsArray(array $lettersArray) {
        $this->setDrops(implode('', $lettersArray));
    }

    public function getDropsArray() {
        return str_split($this->getDrops());
    }

    public function addToDrops($letters) {
        $this->setDrops($this->getDrops().$letters);
    }

    public function removeFromDrops($letters) {
        return $this->removeFromDropsArray(str_split($letters));
    }
    
    public function removeFromDropsArray(array $lettersArray) {
        $dropsArray = $this->getDropsArray();
        foreach ($lettersArray as $letter) {
            $index = array_search($letter, $dropsArray);
            unset($dropsArray[$index]);
        }
        $this->setDropsArray(array_diff($dropsArray, $lettersArray));
    }
    
}
