<?php

/**
 * UserBotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserBotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserBotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserBot');
    }

    public function getByBotIdQuery($botId) {
        return $this->createQuery('ur')
            ->andWhere('ur.bot_id = ?', $botId)
    ;}

    public function getByUserIdAndBotIdQuery($userId, $botId) {
        return $this->getByBotIdQuery($botId)
            ->andWhere('ur.user_id = ?', $userId)
    ;}

}
