<?php

/**
 * UserRealmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserRealmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserRealmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserRealm');
    }

    public function getByUserIdAndRealmIdQuery($userId, $realmId) {
        return $this->createQuery('ur')
            ->where('ur.user_id = ?', $userId)
            ->andWhere('ur.realm_id = ?', $realmId)
    ;}

    public function countByUserIdAndRealmId($userId, $realmId) {
        return $this->getByUserIdAndRealmIdQuery($userId, $realmId)->count();
    }

}
