<?php

/**
 * UserRealmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserRealmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserRealmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserRealm');
    }

    public function getByRealmIdQuery($realmId) {
        return $this->createQuery('ur')
            ->andWhere('ur.realm_id = ?', $realmId)
    ;}

    public function getByUserIdAndRealmIdQuery($userId, $realmId) {
        return $this->getByRealmIdQuery($realmId)
            ->andWhere('ur.user_id = ?', $userId)
    ;}

    public function countByRealmId($realmId) {
        return $this->getByRealmIdQuery($realmId)->count();
    }

    public function countByUserIdAndRealmId($userId, $realmId) {
        return $this->getByUserIdAndRealmIdQuery($userId, $realmId)->count();
    }

    public function getUserIdsByRealmId($realmId) {
        return (array)$this->getByRealmIdQuery($realmId)->select('ur.user_id')->execute(array(), Doctrine::HYDRATE_SINGLE_SCALAR);
    }

}
