#!/bin/bash

cat doc/tutorial | perl -p -e "s/(... is a no-go|Argh, no use)/failure/g;" | grep -P "^(rk|robot|failure)" | perl -p -e "s/\s+#.*//g;" -e "s/rk (.*)/->when('Exec', '\1')/g;" -e "s/robot \[(\w+)\]/\t->given('Robot', '\1')/g;" -e "s/\[(\w+)\]/'.\\\$this->getRobotId('\1').'/g;" -e "s/(\w+)RobotID/lc(\$1)/ge;" -e "s/failure.*/->then('Failure')/g;" -e "s/tea/tea1/g;" -e "s/.''//g;" -e "s/(->(?:when|given).*)/\1\n->then('Success')/;"



