<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/05 13:21:25

return array(
'doctrine1' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:////home/malyutik/workspace/robotics/lib/symfony/lib/plugins/sfDoctrinePlugin/test/functional/fixtures/data/database1.sqlite',
  'name' => 'doctrine1',
)),

'doctrine2' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:////home/malyutik/workspace/robotics/lib/symfony/lib/plugins/sfDoctrinePlugin/test/functional/fixtures/data/database2.sqlite',
  'name' => 'doctrine2',
)),

'doctrine3' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:////home/malyutik/workspace/robotics/lib/symfony/lib/plugins/sfDoctrinePlugin/test/functional/fixtures/data/database3.sqlite',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine3',
)),);
